### ISSUE TITLE
Update to 0.19.1

### ISSUE THREAD

**Issue by jxxcarlson** [Punie/elm-stlc#1]
Hi, I am very interested in this project, but was not able to build it.  I changed the Elm version to 0.19.1 in `elm.json`, but `npm install` failed (see **Log** below).  I also tried building things by hand:

- `npm install -g tsc`
- `elm make src/elm/Main.elm --output=dist/stlc.js --optimize`
- Copy the contents of `./src/ts` to `./dist`
-  `node ./dist/app.js`

The error was

```
 $ node ./dist/app.js
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/Users/carlson/dev/elm/experiments/elm-stlc/dist/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Sanity check:

```
$ ls ./dist
app.ts		repl.ts		runner.ts	stlc.d.ts	stlc.js
```

**Log:**

```
npm install
npm WARN deprecated elm@0.19.1: package.json was changed upon upload, breaking things on Mac and Linux

> elm@0.19.1 install /Users/carlson/dev/elm/experiments/elm-stlc/node_modules/elm
> node install.js

--------------------------------------------------------------------------------

Downloading Elm 0.19.1 from GitHub.

NOTE: You can avoid npm entirely by downloading directly from:
https://github.com/elm/compiler/releases/download/0.19.1/binary-for-mac-64-bit.gz
All this package does is download that file and put it somewhere.

--------------------------------------------------------------------------------

internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:981:7)
    at module.exports (/Users/carlson/dev/elm/experiments/elm-stlc/node_modules/elm/download.js:26:24)
    at Object.<anonymous> (/Users/carlson/dev/elm/experiments/elm-stlc/node_modules/elm/install.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.19.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm@0.19.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carlson/.npm/_logs/2020-01-25T23_15_07_227Z-debug.log
```

**Comment by Punie** [comment]
Hi! Thank you for the report. To be honest, I haven't revisited this project in quite a while.

Weirdly, I couldn't reproduce the exact errors you faced, but there were errors nonetheless.
I made the various upgrades and changes needed to make this work again. It seems to be working on my computer, could you give it a try and let me know if you still are having issues running it?
